## Numpy Array

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4],dtype=int)
arr

array([1, 2, 3, 4])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr=np.array([1,2,3,4],dtype=int,ndmin=10)
arr

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [5]:
#autometic downcasting
np.array([[1,2],[4,6.0]])

array([[1., 2.],
       [4., 6.]])

In [6]:
arr=np.array([1,2,3,4],dtype=complex,ndmin=10)
arr

array([[[[[[[[[[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j]]]]]]]]]])

In [7]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [8]:
np.mat([[1,2],[5,6,7]])

matrix([[list([1, 2]), list([5, 6, 7])]], dtype=object)

In [9]:
np.mat([[1,2],[5,6]])

matrix([[1, 2],
        [5, 6]])

## Numpy.asarray

In [15]:
a=np.array([1,2])


In [18]:
np.asarray([1,2]) is a

False

In [19]:
np.asanyarray([1,2]) is a

False

In [20]:
a=np.matrix([1,2])
np.asanyarray(a)

matrix([[1, 2]])

In [21]:
a=np.matrix([1,2])
np.asarray(a)

array([[1, 2]])

In [22]:
a=np.matrix([1,2])
np.array(a)

array([[1, 2]])

In [23]:
a=np.array([1,2])
x=a

In [24]:
x[0]=5

In [25]:
x

array([5, 2])