In [2]:
import numpy as np

## Reshape

In [12]:
s=np.arange(16).reshape(2,8)

In [4]:
np.arange(16).reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [8]:
x=np.arange(16).reshape(4,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Diagonal

In [9]:
np.diag(x)

array([ 0,  5, 10, 15])

In [10]:
np.diag(x,k=2)

array([2, 7])

In [11]:
np.diag(x,k=-1)

array([ 4,  9, 14])

In [13]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [14]:
np.diag(s,k=-1)

array([8])

In [17]:
np.diag(s,k=3)

array([ 3, 12])

In [19]:
#extract diagonal element from the matrix in array fromat

In [20]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.diag(np.diag(x,k=-1))

array([[ 4,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 14]])

##  numpy.diagflat

In [25]:
np.diagflat([[1,2],[3,4]],k=5)

array([[0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.diagflat([1,2],k=1 )

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

## np.tri()
- array with the ones at the below diagonal and else filled with the zeros


In [32]:
np.tri(3,3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [33]:
np.tri(3,3,k=1)

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.tri(3,3,k=2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.tri(5,5,k=1)

array([[1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.tri(3,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [40]:
np.tri(3,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [43]:
np.tri(5,7,k=1)

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0.]])

## np.tril()


In [44]:
#return a lower tringle of array
#try to fill lower tringle

In [47]:
np.tril(x,k=1)

array([[ 0,  1,  0,  0],
       [ 4,  5,  6,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## np.triu()

In [50]:
#return a upper tringle of array
#try to fill upper tringle

In [49]:
np.triu(x,k=1)

array([[ 0,  1,  2,  3],
       [ 0,  0,  6,  7],
       [ 0,  0,  0, 11],
       [ 0,  0,  0,  0]])

# Random Number Generator

In [51]:
#np.random.rand  -->generate random data between (0,1) Unifrom distribution
#np.random.randn-->generate the matrix from the standard normal distribution-->mean=0,std=1
#np.random.randint-->generate random int number between given range

In [52]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.76928293 0.11450029 0.8517007 ]
 [0.44031932 0.31343821 0.20512273]]


In [53]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.81097604 -0.16355466 -0.37630998]
 [-0.81657292 -0.69915979  0.26622476]
 [-0.69979858 -0.52994949 -0.95280956]
 [ 0.62808071  2.05029672  1.00470749]]


In [56]:
print("Random integer vector:",np.random.randint(1,30)) #randint (low, high, # of samples to be drawn)

Random integer vector: 5


In [57]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[60 72  7 49]
 [ 1 90 35 35]
 [85 34 56 97]
 [70 54 57 61]]

20 samples drawn from a dice throw: [3 1 6 5 1 1 5 3 1 4 2 6 2 4 5 4 1 4 2 5]


## Reshaping

In [58]:
from numpy.random import randint as ri

In [62]:
a=ri(1,100,30)
b=a.reshape(2,5,3)
c=a.reshape(6,-456)


In [63]:
c

array([[32, 94, 23, 70, 25],
       [84, 78, 45, 86, 53],
       [76, 80, 86, 76, 13],
       [68, 25, 24, 78, 11],
       [ 6, 68, 71, 38,  1],
       [37, 10, 19, 55, 74]])

In [64]:
print('shape of a:',a.shape)
print('shape of b',b.shape)
print('shape of c',c.shape)

shape of a: (30,)
shape of b (2, 5, 3)
shape of c (6, 5)


In [65]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [32 94 23 70 25 84 78 45 86 53 76 80 86 76 13 68 25 24 78 11  6 68 71 38
  1 37 10 19 55 74] 
 --------------------

b looks like
 -------------------- 
 [[[32 94 23]
  [70 25 84]
  [78 45 86]
  [53 76 80]
  [86 76 13]]

 [[68 25 24]
  [78 11  6]
  [68 71 38]
  [ 1 37 10]
  [19 55 74]]] 
 --------------------

c looks like
 -------------------- 
 [[32 94 23 70 25]
 [84 78 45 86 53]
 [76 80 86 76 13]
 [68 25 24 78 11]
 [ 6 68 71 38  1]
 [37 10 19 55 74]] 
 --------------------


In [73]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [18 58 56 26 11  5 27 41 90 59]

Here is the sorted vector
 -------------------------------------------------- 
 [ 5 11 18 26 27 41 56 58 59 90]


In [78]:
M=ri(1,100,25).reshape(5,5)
M

array([[53, 38, 46,  3, 92],
       [34, 24, 83, 84, 37],
       [31, 90, 69, 49, 40],
       [89, 79, 47, 67, 72],
       [67, 77, 46, 97, 84]])

In [81]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[29 75 86 95 97]
 [31 33 45 76 81]
 [26 59 65 85 99]
 [ 6  9 65 76 93]
 [ 1  2 24 50 89]]


array([[75, 86, 97, 29, 95],
       [33, 81, 45, 31, 76],
       [26, 85, 99, 59, 65],
       [76, 93,  9, 65,  6],
       [ 1, 50,  2, 24, 89]])