In [2]:
import numpy as np

## Reshape

In [12]:
s=np.arange(16).reshape(2,8)

In [4]:
np.arange(16).reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [8]:
x=np.arange(16).reshape(4,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Diagonal

In [9]:
np.diag(x)

array([ 0,  5, 10, 15])

In [10]:
np.diag(x,k=2)

array([2, 7])

In [11]:
np.diag(x,k=-1)

array([ 4,  9, 14])

In [13]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [14]:
np.diag(s,k=-1)

array([8])

In [17]:
np.diag(s,k=3)

array([ 3, 12])

In [19]:
#extract diagonal element from the matrix in array fromat

In [20]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.diag(np.diag(x,k=-1))

array([[ 4,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 14]])

##  numpy.diagflat

In [25]:
np.diagflat([[1,2],[3,4]],k=5)

array([[0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.diagflat([1,2],k=1 )

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

## np.tri()
- array with the ones at the below diagonal and else filled with the zeros


In [32]:
np.tri(3,3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [33]:
np.tri(3,3,k=1)

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.tri(3,3,k=2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.tri(5,5,k=1)

array([[1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.tri(3,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [40]:
np.tri(3,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [43]:
np.tri(5,7,k=1)

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0.]])

## np.tril()


In [44]:
#return a lower tringle of array
#try to fill lower tringle

In [47]:
np.tril(x,k=1)

array([[ 0,  1,  0,  0],
       [ 4,  5,  6,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## np.triu()

In [50]:
#return a upper tringle of array
#try to fill upper tringle

In [49]:
np.triu(x,k=1)

array([[ 0,  1,  2,  3],
       [ 0,  0,  6,  7],
       [ 0,  0,  0, 11],
       [ 0,  0,  0,  0]])

# Random Number Generator

In [51]:
#np.random.rand  -->generate random data between (0,1) Unifrom distribution
#np.random.randn-->generate the matrix from the standard normal distribution-->mean=0,std=1
#np.random.randint-->generate random int number between given range

In [52]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.76928293 0.11450029 0.8517007 ]
 [0.44031932 0.31343821 0.20512273]]


In [53]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.81097604 -0.16355466 -0.37630998]
 [-0.81657292 -0.69915979  0.26622476]
 [-0.69979858 -0.52994949 -0.95280956]
 [ 0.62808071  2.05029672  1.00470749]]


In [56]:
print("Random integer vector:",np.random.randint(1,30)) #randint (low, high, # of samples to be drawn)

Random integer vector: 5


In [57]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[60 72  7 49]
 [ 1 90 35 35]
 [85 34 56 97]
 [70 54 57 61]]

20 samples drawn from a dice throw: [3 1 6 5 1 1 5 3 1 4 2 6 2 4 5 4 1 4 2 5]


## Reshaping

In [58]:
from numpy.random import randint as ri

In [62]:
a=ri(1,100,30)
b=a.reshape(2,5,3)
c=a.reshape(6,-456)


array([[32, 94, 23, 70, 25],
       [84, 78, 45, 86, 53],
       [76, 80, 86, 76, 13],
       [68, 25, 24, 78, 11],
       [ 6, 68, 71, 38,  1],
       [37, 10, 19, 55, 74]])

In [64]:
print('shape of a:',a.shape)
print('shape of b',b.shape)
print('shape of c',c.shape)

shape of a: (30,)
shape of b (2, 5, 3)
shape of c (6, 5)


In [65]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [32 94 23 70 25 84 78 45 86 53 76 80 86 76 13 68 25 24 78 11  6 68 71 38
  1 37 10 19 55 74] 
 --------------------

b looks like
 -------------------- 
 [[[32 94 23]
  [70 25 84]
  [78 45 86]
  [53 76 80]
  [86 76 13]]

 [[68 25 24]
  [78 11  6]
  [68 71 38]
  [ 1 37 10]
  [19 55 74]]] 
 --------------------

c looks like
 -------------------- 
 [[32 94 23 70 25]
 [84 78 45 86 53]
 [76 80 86 76 13]
 [68 25 24 78 11]
 [ 6 68 71 38  1]
 [37 10 19 55 74]] 
 --------------------


In [73]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [18 58 56 26 11  5 27 41 90 59]

Here is the sorted vector
 -------------------------------------------------- 
 [ 5 11 18 26 27 41 56 58 59 90]


In [78]:
M=ri(1,100,25).reshape(5,5)
M

array([[53, 38, 46,  3, 92],
       [34, 24, 83, 84, 37],
       [31, 90, 69, 49, 40],
       [89, 79, 47, 67, 72],
       [67, 77, 46, 97, 84]])

In [82]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[15  8 19  7 39]
 [46  9 32 17 40]
 [60 19 44 25 64]
 [61 27 59 38 70]
 [93 45 98 96 90]]


array([[61,  9, 44, 96, 40],
       [15,  8, 98, 25, 90],
       [46, 19, 59, 38, 64],
       [93, 27, 19,  7, 70],
       [60, 45, 32, 17, 39]])

In [83]:
print('Maximum of the matrix M:',M.max())


Maximum of the matrix M: 98


In [84]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", M.argmax())


Max of a location: [3 2 4 0 0]
Max of b location: 7


## indexing and slicing

In [86]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr[0]

0

In [89]:
arr[-1:-6]

array([], dtype=int32)

In [90]:
import numpy as np

In [92]:
mat=np.array(ri(10,100,45)).reshape(3,5,3)
mat

array([[[59, 73, 14],
        [63, 99, 72],
        [44, 66, 96],
        [20, 87, 24],
        [69, 96, 51]],

       [[68, 75, 22],
        [61, 88, 79],
        [46, 52, 77],
        [24, 69, 10],
        [77, 58, 59]],

       [[35, 44, 23],
        [59, 91, 66],
        [64, 20, 65],
        [38, 53, 51],
        [24, 84, 47]]])

In [122]:
mat[0:3,:2]

array([[[59, 73, 14],
        [63, 99, 72]],

       [[68, 75, 22],
        [61, 88, 79]],

       [[35, 44, 23],
        [59, 91, 66]]])

## Subseting

In [125]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[45 73 29 74 98]
 [12 70 95 74 86]
 [70 63 81 99 94]]


array([[False,  True, False,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [126]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [73 74 98 70 95 74 86 70 63 81 99 94]


## Universal Functions

In [131]:
ma1=ri(1,10,9).reshape(3,3)
ma2=ri(1,10,9).reshape(3,3)

In [134]:
ma1,ma2

(array([[8, 1, 8],
        [1, 2, 9],
        [5, 2, 4]]),
 array([[7, 6, 6],
        [2, 1, 7],
        [9, 2, 4]]))

In [135]:
ma1*ma2

array([[56,  6, 48],
       [ 2,  2, 63],
       [45,  4, 16]])

In [136]:
ma1 @ma2

array([[130,  65,  87],
       [ 92,  26,  56],
       [ 75,  40,  60]])

In [137]:
ma1+ma2

array([[15,  7, 14],
       [ 3,  3, 16],
       [14,  4,  8]])

In [138]:
ma1/0

C:\Users\JESAL\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [139]:
ma1**3

array([[512,   1, 512],
       [  1,   8, 729],
       [125,   8,  64]], dtype=int32)

In [141]:
pow(ma1,3)

array([[512,   1, 512],
       [  1,   8, 729],
       [125,   8,  64]], dtype=int32)

In [142]:
100+ma1

array([[108, 101, 108],
       [101, 102, 109],
       [105, 102, 104]])

## Broadcasting

In [143]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.

In [144]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [145]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [150]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [152]:
# create an ndarray which is 4 x 1 to broadcast across columns (Tranpose)
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [153]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


## Array Math

In [154]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[9 8 3]
 [7 1 7]
 [7 1 8]]

2nd Matrix of random single-digit numbers
------------
 [[8 7 6]
 [8 4 4]
 [2 5 6]]


In [155]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[1 1 3]
 [7 1 3]
 [1 1 2]]


array([[1, 1, 3],
       [7, 1, 3],
       [1, 1, 2]], dtype=int32)

In [156]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.95424251 0.90308999 0.47712125]
 [0.84509804 0.         0.84509804]
 [0.84509804 0.         0.90308999]]
[[9 8 3]
 [7 1 7]
 [7 1 8]]
[[8 7 6]
 [8 4 4]
 [2 5 6]]


In [157]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[8.10308393e+03 2.98095799e+03 2.00855369e+01]
 [1.09663316e+03 2.71828183e+00 1.09663316e+03]
 [1.09663316e+03 2.71828183e+00 2.98095799e+03]]


In [158]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[3.         2.82842712 1.73205081]
 [2.64575131 1.         2.64575131]
 [2.64575131 1.         2.82842712]]
