## Numpy Array

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4],dtype=int)
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr=np.array([1,2,3,4],dtype=int,ndmin=10)
arr

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [6]:
#autometic downcasting
np.array([[1,2],[4,6.0]])

array([[1., 2.],
       [4., 6.]])

In [7]:
arr=np.array([1,2,3,4],dtype=complex,ndmin=10)
arr

array([[[[[[[[[[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j]]]]]]]]]])

In [8]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [9]:
np.mat([[1,2],[5,6,7]])

matrix([[list([1, 2]), list([5, 6, 7])]], dtype=object)

In [10]:
np.mat([[1,2],[5,6]])

matrix([[1, 2],
        [5, 6]])

## Numpy.asarray

In [11]:
a=np.array([1,2])


In [12]:
np.asarray([1,2]) is a

False

In [13]:
np.asanyarray([1,2]) is a

False

In [14]:
a=np.matrix([1,2])
np.asanyarray(a)

matrix([[1, 2]])

In [15]:
a=np.matrix([1,2])
np.asarray(a)

array([[1, 2]])

In [16]:
a=np.matrix([1,2])
np.array(a)

array([[1, 2]])

In [17]:
a=np.array([1,2])
x=a

In [18]:
x[0]=5

In [19]:
x

array([5, 2])

In [20]:
a[1]=4#shallow copy
a,x


(array([5, 4]), array([5, 4]))

In [22]:
z=np.copy(x) #deep copy
z[0]=9
z,x

(array([9, 4]), array([5, 4]))

## Numpy.fromfunction

In [24]:
#Construct an array by executing a function over each coordinate.

In [26]:
np.fromfunction(lambda i,j :i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i,j,k :i*j*k,(4,2,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2]],

       [[0, 0, 0],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 3, 6]]])

## Numpy.fromiter

In [ ]:
#create array from the iterable object

In [36]:
data=(x*x for x in range(5))

In [37]:
np.fromiter(data,dtype=int) 

array([ 0,  1,  4,  9, 16])

## Numpy.fromstring

In [ ]:
#create array from the string object

In [38]:
np.fromstring('123 456',sep=' ')

array([123., 456.])

In [ ]:
#create bundle of array

In [39]:
x1=np.array([1,2,3,4,5])
x2=np.array([1.1,6,7,8,9])
x3=np.array(['a','bb','ccc','d','ee'])
x4=np.array([67,68,69,70,71])


In [42]:
r=np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 1.1, 'a', 67), (2, 6. , 'bb', 68), (3, 7. , 'ccc', 69),
           (4, 8. , 'd', 70), (5, 9. , 'ee', 71)],
          dtype=[('a', '<i4'), ('b', '<f8'), ('c', '<U3'), ('d', '<i4')])

In [47]:
r[0]['a']

1

## DataTypes

In [49]:
mylist=[1,2,3,4,5]
arr=np.array(mylist)
print('type of class/object:',type(arr))
print('\n here is the vector\n----------------------------\n',arr)

type of class/object: <class 'numpy.ndarray'>

 here is the vector
----------------------------
 [1 2 3 4 5]


In [55]:
myli=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(myli)
print('matrix:',arr)
print('dimenstion of array:',arr.ndim)
print('shape of array',arr.shape)
print('size of array',arr.size)
print('type of array',arr.dtype)

#even tuples cabe converted into array

matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimenstion of array: 2
shape of array (3, 3)
size of array 9
type of array int32
